#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Oct 27 12:40:48 2020

@author: bananabelyong
"""

def main():
    filename = str(input("Input file name : "))
    filein = open(filename, "r")            # Open file for reading


    input_data = filein.readlines()         # Read in data as list of strings

    for line in input_data:                 # Scan through writing lines
        print(line)                         # Note extra "\n" problem 

    for line in input_data:
        print (line[:-1])               # This removes the last character


    filein.close(filename, "r")
    
main()